Feature/dataloader
artefactory/NLPretext pull request #152
Opened 2021-06-02 17:02 UTC by sachalasry-artefact

Added a class to easily load text data using Dask, whether it is stored locally or on GCS. The TextLoader class can be fetched with a single path, but also with a list of path, that may contain wildcards

2021-06-03 07:48 UTC, hugovasselin requested changes
Bravo Sacha hyper propre ! A part une petite coquille dans le readme pas grand chose à changer mais plutôt des pistes de réflexions :) 

Notamment la dépendance à Dask obligatoire ca peut rendre la lib plus lourde et compliquée à installer

2021-06-03 07:48 UTC, hugovasselin commented on README.md
> +Pre-processing text data is useful only if you have loaded data to process ! Importing text data as strings in your code can be really simple if you have short texts contained in a local .txt, but it
pas d'espace entre le mot et la ponctuation en anglais: 
```if you have loaded data to process !``` --> ```if you have loaded data to process!```

2021-06-03 07:48 UTC, hugovasselin commented on README.md
> +# ["I just got the best dinner in my life !!!",  "I recommend", "It was awesome"]
idem pas d'espace :)  ```"I just got the best dinner in my life !!!"```

2021-06-03 07:48 UTC, hugovasselin commented on README.md
> +gcs_corpus_path = "gs://my-bucket/texts/text_*.json" # Multiple files from GCS with wildcard
trop cool cette feature! est-ce qu'un support S3 est prévu :) ?

2021-06-03 07:48 UTC, hugovasselin commented on README.md
> +preprocessed_text_dataframe = text_loader.read_text(local_file_path, preprocessor=preprocessor)
Ca pourrait être cool que "text_loader"  ai une méthode "preprocess" qu'on puisse chainer, à la pandas

2021-06-03 08:02 UTC, sachalasry-artefact commented on README.md
> +gcs_corpus_path = "gs://my-bucket/texts/text_*.json" # Multiple files from GCS with wildcard
J'avoue que j'ai seulement mis GCS et local parce que c'est ce que j'ai pu tester, mais ça fonctionne aussi avec S3, HDFS et Azure, je vais ajouter ça dans la doc ! :)

2021-06-03 08:12 UTC, sachalasry-artefact commented on nlpretext/textloader.py
> +        is_computed: bool
J'ai peur que cela crée la confusion que cela ne nécessitera pas de calcul supplémentaire, alors que la conversion en pandas est ce qui au final va être lourd en calcul. 

Mais je peux mettre quelque chose du style "convert_to_pandas" ou "compute_as_pd_df"

2021-06-03 08:49 UTC, sachalasry-artefact commented on README.md
> +preprocessed_text_dataframe = text_loader.read_text(local_file_path, preprocessor=preprocessor)
Les textes ne sont pas stockés dans la classe directement, donc pas sûr de voir quelle serait la meilleure façon de faire

2021-06-03 09:16 UTC, sachalasry-artefact commented on nlpretext/textloader.py
> +import dask.bag as db
A voir en P2 du coup je pense, il faudrait créer des méthodes supplémentaires qui gèrent les wildcards et les appels aux différents providers. 

En attendant je mets l'installation de dask en requirements dev avec un try import pour pas forcer l'installation à tous les users

2021-06-17 14:40 UTC, amaleelhamri commented
C'est parfait Sacha merci!! Est-ce qu'on peut juste upgrade la version avant de merge ?

2021-06-17 14:45 UTC, hugovasselin submitted a review, later dismissed
Top merci Sacha!

2021-06-17 14:48 UTC, rafaelleaygalenq commented on README.md
> +# Load text data
Possible de rajouter une phrase dans le Readme pour l'installation de Dask ? Etant donné que c'est pas dans les requirements, juste préciser qu'il faut l'installer si l'utilisateur veut se servir du dataloader. Tu peux le mettre juste après les pip install de spacy :)

2021-06-17 15:24 UTC, sachalasry-artefact commented on README.md
> +# Load text data
Yes bonne idée, merci :)

2021-06-17 15:36 UTC, rafaelleaygalenq approved these changes

2021-06-21 13:09 UTC, merged